// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>

using std::cout;
using std::cin;
using std::endl;

int main(){
    int soma = 0;
    int a = 1;
    int b = 2;

    for(int i = 0; b <= 4000000; i++){
        if (b % 2 == 0){
            soma = soma + b;
        }
        else{
            soma = soma;
        }
        int c = a + b;
        a = b;
        b = c;
    }
    cout << "A soma dos números pares da sequência de Fibonacci é: " << soma << endl;
    return 0;
}
